/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kulmanm' at '8/1/18 6:14 AM' with Gradle 2.9
 *
 * @author kulmanm, @date 8/1/18 6:14 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
